### PR TITLE
Updated doc

### PR DESCRIPTION
**Pull request by EdwinGuzman**
New version with updated package-lock file. It wasn't committed with the latests package updates and @helenvholmes had a hard time running the app locally. Also updating the instructions for committing to the project and hope it's simplier. @nonword I added you because I saw you checked Kang's PRs but not necessary if you can't review.

### CODE REVIEW

**Comment by helenvholmes** [comment]
👍🏻

**Comment by EdwinGuzman** [comment]
I'm using node 8 locally but I remember you had a PR where 6 was the version that was optimal on Travis for tests? I can change it to 6.

**Comment by nonword** [comment]
Cool. Whether 6 or 8, app should be explicit. For compatibility with the apps that include it, we should prob settle on 6. I'll file a PR later to add an `.nvmrc`

**Comment by EdwinGuzman** [comment]
Thanks, Paul.

**Pull request merged**
