### PR TITLE
Fix focus overlay #7

### PR DESCRIPTION
**Pull request by ricardoom**
modified a bit margins in the top nav to fix the focus overlap.

### CODE REVIEW

**Comment by ricardoom** [comment]
Is it cool if I merge this despite the Travis checking failing?

**Comment by EdwinGuzman** [comment]
I'd like not to. Let me see if I can find what's wrong first.

**Comment by EdwinGuzman** [comment]
I know what's wrong but it's odd you don't have this update. I'll merge and fix development, but the issue is you don't have the new babel es2015 preset in your branch, which should normally be okay, but I guess since the recent branches have been different, it's now not working.

**Comment by EdwinGuzman** [comment]
And it's also because there's no .yml config file. No worries about this.

**Pull request merged**
