### PR TITLE
Updating focus style for logged in menu.

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Adding missing focus style for the logged in state in the drop down menu. 

screen shot 2018-07-12 at 4 05 57 pm

### CODE REVIEW

**Comment by ktp242** [comment]
Looks good. We should also update the changelog for the new feature.

**Comment by EdwinGuzman** [comment]
No? It's not a new feature. It was just missed on the first pass of adding that focus ring to the elements.

**Comment by ktp242** [comment]
I looked into the change log of 2.4.10 for development and it only mentions the focus styles on mobile view. The change log related to the focus styles for buttons and links are from 2.4.9. I think it is minor and also really depends on different point of view so I will leave you to decide :-)

**Comment by ktp242** [comment]
Will this fix also fix the focus ring for mobile view's logged in? I don't see relate changes. But on dev, I can see the outline is white now yet with slightly different styles. It looks a bit blur than other outlines.

**Comment by EdwinGuzman** [comment]
Updated to have a better solid outline on mobile logged in. And yes, if you checked the code, I added focus style for both mobile/desktop logged in states.

**Pull request merged**
